### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by higuken** [higuken/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by higuken** [comment]
これから対応します。

**Comment by katakasu** [comment]
fc7ec4で対応されました。

**Comment by katakasu** [comment]
fc7ec4 で対応されました。

**Comment by higuken** [comment]
fc7ec4 で対応されました。
